export const data = [
    {
        id:1,
        name: 'Esaac Dell House.',
        location: '18B Central Street, Sun Francisco',
        date: 'Added: March 8, 2023',
        price: '155200',
        image: '/images/pic.jpeg',
        status: 'for sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
  
    {
        id:2,
        name: 'Gose Hill Mansion.',
        location: '194 Mercer Street, Washington',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic2.jpeg',
        status: 'For Buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:3,
        name: 'Parriet Whillips Dungalow.',
        location: '5B Central Street, California',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic3.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:4,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic4.jpeg',
        status: 'For Buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:5,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic5.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:6,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic6.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:7,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic7.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:8,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic8.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:9,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic9.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:10,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic10.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:11,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic11.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:12,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic12.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:13,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic13.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:14,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic14.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:15,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic15.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:16,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic16.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:17,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic17.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:18,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic18.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:19,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic19.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:20,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic20.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:21,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic21.jpeg',
        status: 'For Co-Living',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:22,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic22.jpeg',
        status: 'For buy',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:23,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic23.jpeg',
        status: 'For sale',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    },
    {
        id:24,
        name: 'Solly Nrown House.',
        location: '18B Central Street, Chicago',
        date: 'Added: March 8, 2023',
        price: '255300',
        image: '/images/pic24.jpeg',
        status: 'For Co-Living ',
        size: '1450',
        amenities: '3 Bed - 2 Bath - 1 Garage',
    }
]
