export const data = [
  {
    id: 1,
    name: "Esaac Dell House.",
    location: "18B Central Street, San Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house1.jpg",
    status: "for rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    add: "explore",
  },

  {
    id: 2,
    name: "Duplex de Villa.",
    location: "18B Central Street, New York",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house2.jpg",
    status: "for sale",
    size: "1451",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    add: "explore",
  },

  {
    id: 3,
    name: "Orchid Casel de Paradise.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house3.jpg",
    status: "for buy",
    size: "1452",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    add: "explore",
  },
  {
    id: 4,
    name: "Orchid Casel de Evian.",
    location: "18B Central Street, Sun Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house4.jpg",
    status: "for sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },

  {
    id: 5,
    name: "Gose Hill Mansion.",
    location: "194 Mercer Street, Washington",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house5.jpg",
    status: "For rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 6,
    name: "Parriet Whillips Dungalow.",
    location: "5B Central Street, California",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house6.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 7,
    name: "Ruposibangla de Omo.",
    location: "18A Central Street, New York",
    date: "Added: March 8, 2023",
    price: "155300",
    image: "/images/house7.jpg",
    status: "For Buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    place: "New York",
  },
  {
    id: 8,
    name: "Kelvin Studio Palace.",
    location: "18B Central Street, New York",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house8.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    place: "New York",
  },
  {
    id: 9,
    name: "Gose Hill Mansion.",
    location: "18C Central Street, New York",
    date: "Added: March 8, 2023",
    price: "355300",
    image: "/images/house9.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    place: "New York",
  },
  {
    id: 10,
    name: "Damola Garden Resedence.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house10.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    place: "Chicago",
  },
  {
    id: 11,
    name: "Elite Garden Resedence.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house11.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 12,
    name: "kelvin Villa.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house3.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
    place: "Chicago",
  },
  {
    id: 13,
    name: "David Villa.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house1.jpg",
    status: "For rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 14,
    name: "Emekus Appartment.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house4.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 15,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house8.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 16,
    name: "Gose Hill Mansion.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house16.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 17,
    name: "Esaac Dell House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house17.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 18,
    name: "Parriet Whillips Dungalow.",
    location: "18B Central Street, New York",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house2.jpg",
    status: "For rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 19,
    name: "Darold Lloyd Estate.",
    location: "18B Central Street, New York",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house1.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 20,
    name: "Sinomen plant Palace.",
    location: "18B Central Street,New York",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house1.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 21,
    name: "Duplex de Villa.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house1.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 22,
    name: "Orchid Casel de Paradise.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house22.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 23,
    name: "Ruposibangla de parlosia.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house23.jpg",
    status: "For rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 24,
    name: "Sinomen Studio Palace.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house24.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 25,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house25.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 26,
    name: "Elite Garden Resedence.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house26.jpg",
    status: "For rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
 

  {
    id: 28,
    date: ". MD Mat HT . january 8, 2021",
    image: "/images/house7.jpg",
    blog: "updated",
    writeup1: "Importance of Build quality of modern Real Estate.",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
  },

  {
    id: 29,
    date: ". FD Luke FT . May 4, 2022",
    image: "/images/house1.jpg",
    blog: "updated",
    writeup1: "Importance of Build quality of modern Real Estate.",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
 
  },

  {
    id: 30,
    date: ". Ak John JT . Febuary 8, 2022",
    image: "/images/house2.jpg",
    blog: "updated",
    writeup1: "18 Best Real Estate Apps For Buyers, Sellers & Investors.",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
 
  },

  {
    id: 31,
    date: ". PQ Mark BT . June 2, 2024",
    image: "/images/house3.jpg",
    blog: "updated",
    writeup1: "Most Popular Real Estae area you can choose from.",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
 
  },

  {
    id: 32,
    date: ". PQ Mark BT . June 2, 2024",
    image: "/images/house4.jpg",
    blog: "updated",
    writeup1: "The Home Buying Process: A Comprehensive Guide..",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
 
  },

  {
    id: 33,
    date: ". PQ Mark BT . June 2, 2024",
    image: "/images/house5.jpg",
    blog: "updated",
    writeup1: "Tip’s about Real Estate Recent Conditions from Agent.",
    writeup2: "Properties are the most budget friendly so you have an opportunity to find the best...."
  },



];
