export const data = [
  {
    id: 1,
    name: "Esaac Dell House.",
    add: "18B Central Street, Sun Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house1.jpg",
    status: "for rent",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },

  {
    id: 2,
    name: "Duplex de Villa.",
    add: "18B Central Street, Sun Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house2.jpg",
    status: "for sale",
    size: "1451",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },

  {
    id: 3,
    name: "Orchid Casel de Paradise.",
    add: "18B Central Street, Sun Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house3.jpg",
    status: "for buy",
    size: "1452",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 4,
    name: "Esaac Dell House.",
    location: "18B Central Street, Sun Francisco",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house4.jpg",
    status: "for sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },

  {
    id: 5,
    name: "Gose Hill Mansion.",
    location: "194 Mercer Street, Washington",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house5.jpg",
    status: "For Buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 6,
    name: "Parriet Whillips Dungalow.",
    location: "5B Central Street, California",
    date: "Added: March 8, 2023",
    price: "155200",
    image: "/images/house6.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 7,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house7.jpg",
    status: "For Buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 8,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house8.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 9,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house9.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 10,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house10.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 11,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house11.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 12,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house12.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 13,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house13.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 14,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house14.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 15,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house15.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 16,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house16.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 17,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house17.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 18,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house18.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 19,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house19.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 20,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house20.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 21,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house21.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 22,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house22.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 23,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house23.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 24,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house24.jpg",
    status: "For Co-Living",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 25,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house25.jpg",
    status: "For buy",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 26,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house26.jpg",
    status: "For sale",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
  {
    id: 27,
    name: "Solly Nrown House.",
    location: "18B Central Street, Chicago",
    date: "Added: March 8, 2023",
    price: "255300",
    image: "/images/house27.jpg",
    status: "For Co-Living ",
    size: "1450",
    amenities: "3 Bed - 2 Bath - 1 Garage",
  },
];
